import Sidebar from "../../components/Sidebar";

export default function Reports() {
  return (
    <div style={{ display: "flex" }}>
      <Sidebar />

      <main
        style={{
          padding: "40px",
          flex: 1,
        }}
      >
        <h1>Reports</h1>

        <p>Reports generated by the AI will appear here.</p>
      </main>
    </div>
  );
}
